# General Settings
title: "Espai Consulting 24"
email: "didac@espaiconsulting.com"
email_2: "jaume@espaiconsulting.com"
description: >- # this means to ignore newlines until "baseurl:"
  Espai Consulting 24 transforma ideas audaces en soluciones inteligentes, 
  fusionando tecnología avanzada con estrategias innovadoras para revolucionar tu negocio. 
  Tu visión, nuestro diseño: juntos construimos el futuro.
black_logo_1x: "/assets/images/logo-espai-black.png"
black_logo_2x: "/assets/images/logo-espai-black.png"
light_logo_1x: "/assets/images/logo-light-espai-bg.png"
light_logo_2x: "/assets/images/logo-light-espai-bg.png"

address_01: 'Tàrrega <br>Lleida<br /> España'
phone_number: ""
copyright_text: "© 2024 Espai Consulting 24. All rights reserved."

google_analytics:
  enable: true
  key: "G-RJG88B76PY"  # UA-664136761-1

google_map: |
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3172.4564967931838!2d-122.03250858386237!3d37.33169997984258!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fb5b6e94ffe23%3A0x63bb79532baa6af4!2sApple+Campus!5e0!3m2!1sen!2str!4v1553850783971!5m2!1sen!2str" style="width:100%; height: 100%; border:0" allowfullscreen=""></iframe>

social_accounts:
  title: "Follow Us"
  links:
    - url: "#"
      icon: "jam jam-twitter"

    - url: "#"
      icon: "jam jam-facebook"

    - url: "#"
      icon: "jam jam-instagram"

    - url: "https://www.linkedin.com/company/estudi-espai-consulting-24-sl"
      icon: "jam jam-linkedin"
      
    - url: "#"
      icon: "jam jam-youtube"


external_links:
  title: "Sobre nosotros"
  links:
    - url: "#"
      text: "Nosotros"
    - url: "#"
      text: "Historia"
    - url: "#"
      text: "Proyectos"
    - url: "#"
      text: "Tarifas"
    - url: "#"
      text: "Características"


external_links_02:
  title: "Need Help?"
  links:
    - url: "#"
      text: "Support"
    - url: "#"
      text: "Get Started"
    - url: "#"
      text: "Contact Us"
    - url: "#"
      text: "Terms of Use"
    - url: "#"
      text: "Privacy Policy"


external_links_03:
  title: "Company"
  links:
    - url: "#"
      text: "Nosotros"
    - url: "#"
      text: "Estrategia"
    - url: "#"
      text: "Servicio"
    - url: "#"
      text: "Misión"
    - url: "#"
      text: "Proceso"

footer_newsletter:
  title: "La comunidad"
  sub_title: "Subscribete a nuestra agenda para conocer más sobre IA y sus aplicaciones en tu realidad"
  subscribe_button_text: "Únete"


one_page_nav_settings:
  links:
    - text: "Inicio"
      url: "#home"
    - text: "Servicios"
      url: "#services"
    - text: "Experiences"
      url: "#experiences"
    - text: "Portfolio"
      url: "#portfolio"
    - text: "Testimonials"
      url: "#testimonials"
    - text: "Contact"
      url: "#contact"

author_page_header:
  header_background_image: "/assets/images/art/bg31.jpg"

gallery:
  images:
  - img: "/assets/images/art/z1.svg"
  - img: "/assets/images/art/z2.svg"
  - img: "/assets/images/art/z3.svg"
  - img: "/assets/images/art/z4.svg"
  - img: "/assets/images/art/z5.svg"
  - img: "/assets/images/art/z6.svg"
  - img: "/assets/images/art/z7.svg"
  - img: "/assets/images/art/z8.svg"